version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8088:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    restart: unless-stopped

  appium:
    image: appium/appium:latest
    container_name: appium
    ports:
      - "4723:4723"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RELAXED_SECURITY=true
    volumes:
      - ./jenkins_home/workspace:/var/jenkins_home/workspace:ro
      - ./appiumentrypoint.sh:/appiumentrypoint.sh
    entrypoint: [ "/appiumentrypoint.sh" ]
    restart: unless-stopped
