version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8088:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped


  appium:
    image: appium/appium:latest
    container_name: appium
    ports:
      - "4723:4723"
    environment:
      - RELAXED_SECURITY=true
    command: [ "appium", "--allow-insecure", "chromedriver_autodownload" ]
    restart: unless-stopped